on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up keychain to be used for code signing using Codemagic CLI 'keychain' command
        run: keychain initialize

      - name: Fetch signing files
        run: app-store-connect fetch-signing-files "com.trentiums.crm" --type IOS_APP_STORE --create

      - name: Set up signing certificate
        run: keychain add-certificates

      - name: Set up code signing settings on Xcode project
        run: xcode-project use-profiles

      - name: Build App
        run: xcode-project build-ipa --workspace "IA.xcworkspace" --scheme "IA"

    artifacts:
      files:
        - build/ios/ipa/*.ipa
        - /tmp/xcodebuild_logs/*.log
        - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
