name: Build and Upload iOS App to TestFlight

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install Fastlane
        run: gem install fastlane

      - name: Decode and set up Keychain
        run: |
          # Decode and save the .p12 file
          echo "${{ secrets.IOS_DISTRIBUTION_P12_BASE64 }}" | base64 --decode > ./ios_distribution.p12

          # Create and set up the keychain
          security create-keychain -p "${{ secrets.KEYCHAIN_PASSWORD }}" ios-build.keychain
          security default-keychain -s ios-build.keychain
          security unlock-keychain -p "${{ secrets.KEYCHAIN_PASSWORD }}" ios-build.keychain
          security set-keychain-settings -t 3600 -u ios-build.keychain

          # Import the .p12 certificate
          security import "./ios_distribution.p12" -P "${{ secrets.P12_PASSWORD }}" -A

      - name: Decode and set up provisioning profile
        run: |
          echo "${{ secrets.CRM_MOBILEPROVISION_BASE64 }}" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/CRM.mobileprovision

      - name: Move provisioning profile
        run: mv ./certs/CRM.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Build the iOS App
        run: |
          xcodebuild -workspace CRM.xcworkspace \
                     -scheme CRM \
                     -sdk iphoneos \
                     -configuration AppStoreDistribution \
                     -archivePath $PWD/build/CRM.xcarchive \
                     clean archive | xcpretty

      - name: Export the Archive
        run: |
          xcodebuild -exportArchive \
                     -archivePath $PWD/build/CRM.xcarchive \
                     -exportOptionsPlist ./exportOptions.plist \
                     -exportPath $PWD/build/CRM

      - name: Upload to TestFlight
        run: |
          fastlane pilot upload \
            --ipa $PWD/build/CRM/CRM.ipa \
            --skip_waiting_for_build_processing true
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
